/**
 * @provacx/smart-drawing
 * 
 * Professional HVAC CAD drawing package for ProvacX.
 * Provides a complete drawing editor with Fabric.js canvas,
 * HVAC symbol library, and industry-standard CAD tools.
 */

// Main Editor Component
export { SmartDrawingEditor, type SmartDrawingEditorProps } from './SmartDrawingEditor';

// Individual Components
export {
  DrawingCanvas,
  Toolbar,
  PropertiesPanel,
  SymbolPalette,
  LayersPanel,
  RoomHierarchyPanel,
  DrawingGrid,
  DrawingRulers,
  DrawingPageLayout,
  ZoomIndicator,
  CoordinatesDisplay,
  type DrawingCanvasProps,
  type ToolbarProps,
  type PropertiesPanelProps,
  type SymbolPaletteProps,
  type LayersPanelProps,
  type RoomHierarchyPanelProps,
  type DrawingGridProps,
  type DrawingRulersProps,
  type DrawingPageLayoutProps,
} from './components';

// CAD interaction patterns (state machine, selection, snapping)
export {
  buildInteractionScene,
  createEmptySelection,
  cloneSelection,
  resolveSelectionBoxMode,
  hitTestSelection,
  applyClickSelection,
  applyWindowSelection,
  applyLassoSelection,
  propagateSelection,
  createWallManipulationHandles,
  buildDragDimensionOverlay,
  resolveSmartSnap,
  constrainPointWithShift,
  buildContextMenuModel,
  applyWallPropertyPatch,
  createInitialInteractionState,
  reduceInteractionState,
  CadInteractionController,
  createDelegatedEventAdapter,
  InteractionRenderScheduler,
  DEFAULT_VISUAL_THEME,
  DEFAULT_SNAP_CONFIG,
  normalizeModifiersFromMouseEvent,
  type SelectionLevel,
  type SelectionBoxMode,
  type LassoMode,
  type EntityRef,
  type SelectionState,
  type SelectionOptions,
  type SelectionPropagationOptions,
  type VertexPrimitive,
  type WallPrimitive,
  type RoomPrimitive,
  type InteractionScene,
  type SceneBuildOptions,
  type HandleType,
  type ManipulationHandle,
  type HandleGenerationOptions,
  type InteractionVisualTheme,
  type DimensionOverlay,
  type SnapKind,
  type SnapTarget,
  type AlignmentGuide,
  type SmartSnapConfig,
  type SnapContext,
  type SnapResult,
  type KeyboardModifiers,
  type ContextMenuAction,
  type ContextMenuModel,
  type WallPropertyPatch,
  type InteractionMode,
  type InteractionState,
  type InteractionCommand,
  type InteractionEvent,
  type StateMachineOptions,
  type RenderDirtyFlags,
  type CadInteractionControllerOptions,
  type DelegatedEventAdapterOptions,
} from './components/canvas/cad-interaction';

// Spatial hash for interaction proximity detection
export {
  SpatialHash,
  boundsIntersect as spatialHashBoundsIntersect,
  pointBounds,
  getCoveredCells,
  type HashBounds,
  type SpatialHashItem,
} from './components/canvas/spatial-hash';

// Store
export { useSmartDrawingStore, type SmartDrawingState } from './store';

// Types
export type {
  Point2D,
  Bounds,
  DisplayUnit,
  SplineType,
  SplineSettings,
  DrawingTool,
  Wall2D,
  MaterialType,
  MaterialProperties,
  WallLayer,
  WallLayerThicknessConstraint,
  WallTypeDefinition,
  Room2D,
  Sketch2D,
  IndoorUnit2D,
  OutdoorUnit2D,
  DuctSegment2D,
  RefrigerantLine2D,
  DrainLine2D,
  ControlWiring2D,
  HVACLayout2D,
  BoqSummary,
  PageConfig,
  DrawingLayer,
  HistoryEntry,
} from './types';

// Utilities
export {
  // Geometry
  generateId,
  clamp,
  roundToNearest,
  roundValue,
  lerp,
  lerpPoint,
  distance,
  distanceSquared,
  midpoint,
  angleBetween,
  normalOffset,
  rotatePoint,
  calculatePolygonArea,
  calculateCentroid,
  polygonBounds,
  isPointInPolygon,
  distancePointToSegment,
  segmentsIntersect,
  lineIntersection,
  polylineLength,
  projectPointToPolyline,
  simplifyPolyline,
  findNearestWall,
  mergeBounds,
  expandBounds,
  buildArcPath,
  buildRevisionCloudPath,
  sampleCatmullRom,
  countBy,
  // Splines
  DEFAULT_SPLINE_SETTINGS,
  buildSplinePath,
  getSplineTypes,
  interpolateSpline,
  // Duct Planning
  buildDuctDefaults,
  buildBranchRoute,
  buildDuctPlan,
  generateBoqSummary,
  detectRoomsFromWallGraph,
  applyNestedRoomHierarchy,
  validateNestedRooms,
  MATERIAL_LIBRARY,
  BUILT_IN_WALL_TYPES,
  BUILT_IN_WALL_TYPE_IDS,
  DEFAULT_WALL_TYPE_ID,
  getWallTypeRegistry,
  getWallTypeById,
  getWallLayersForType,
  getDefaultLayerPreset,
  snapCoreThickness,
  resolveWallLayers,
  isWallUsingTypeDefault,
  resizeWallTotalThickness,
  addWallLayer,
  removeWallLayer,
  reorderWallLayers,
  updateWallLayerThickness,
  convertWallCoreMaterial,
  resetWallToTypeDefault,
  createWallFromTypeDefaults,
  normalizeWallForTypeSystem,
  getWallTotalThickness,
  getWallRValue,
  getWallUValue,
  getWallCoreThickness,
  getWallFinishThickness,
  getWallLayerAtDepth,
  createWallComputationFacade,
  type WallLayerOperationResult,
  type LayerPresetType,
  type DuctDefaults,
  applyCornerAngleInput,
  applyCornerAngleDrag,
  suggestRectangularCorner,
  snapAngle,
  solveConstraints,
  buildGraphFromWalls,
  detectWallIntersections,
  PackedRTree,
  boundsIntersect,
  inflateBounds,
  WallEditorEngine,
  type Constraint,
  type ConstraintKind,
  type ConstraintViolation,
  type AngleSolveMode,
  type CornerEditInput,
  type CornerEditOptions,
  type SolveResult,
  type RTreeBounds,
  type RTreeEntry,
  type WallEndpoint,
  type RotationPivot,
  type ThicknessAnchorMode,
  type CollisionPolicy,
  type SelectionMergeMode,
  type SelectionHitMode,
  type DirtyFlags,
  type WallEditorState,
  type WallCollision,
  type WallEditOperationResult,
  type SelectionVisualInfo,
  type WallValidationIssue,
  type CommandLifecycleEvent,
  type WallEditorEvents,
  type WallEditCommand,
  type MutationOptions,
  type MoveWallOptions,
  type ResizeWallOptions,
  type RotateWallOptions,
  type AdjustThicknessOptions,
  type RectangleSelectionOptions,
  type PolygonSelectionOptions,
  type GroupTransformOptions,
  type ParallelMoveOptions,
  type ChainSelectionOptions,
  type ChainTransformOptions,
  type WallEditorEngineOptions,
  type WallEditorEngineInit,
} from './utils';

// Symbol Library
export {
  SYMBOL_LIBRARY,
  SYMBOL_CATEGORIES,
  getSymbolById,
  getSymbolsByCategory,
  searchSymbols,
  getCategoryLabel,
  type SymbolDefinition,
  type SymbolCategory,
} from './data';

// Professional architecture modules
export {
  ProfessionalFloorPlanKernel,
  ParametricModelEngine,
  solveParametricModel,
  autoCleanWallNetwork,
  detectAndLabelRooms,
  validateRoomTopologyDetailed,
  PrecisionToolkit,
  parseCoordinateInput,
  FloorPlanSpatialIndex,
  computeLodDecision,
  cullWallsForViewport,
  cullRoomsForViewport,
  DirtyRegionTracker,
  batchWallsByStyle,
  LazyFloorPlanMetrics,
  CommandHistoryManager,
  SnapshotCommand,
  createFloorPlanFile,
  serializeFloorPlanFile,
  parseFloorPlanFile,
  migrateFloorPlanFile,
  exportFloorPlanToSvg,
  exportFloorPlanToDxf,
  exportFloorPlanToPdfModel,
  importFloorPlanFromJson,
  importFloorPlanFromDxf,
  FLOOR_PLAN_SCHEMA_ID,
  CURRENT_FLOOR_PLAN_VERSION,
  FLOOR_PLAN_JSON_SCHEMA,
  type LinearDimensionConstraint,
  type DimensionChainConstraint,
  type ParameterDefinition,
  type ParametricDiagnostic,
  type ParametricSolveResult,
  type ParametricSolveInput,
  type WallNetworkCleanupOptions,
  type WallNetworkCleanupReport,
  type WallNetworkCleanupResult,
  type RoomAutoDetectResult,
  type CoordinateInputMode,
  type CoordinateInputContext,
  type CoordinateInputResult,
  type DistanceMeasurement,
  type AngleMeasurement,
  type AreaMeasurement,
  type ViewportBounds,
  type VertexRef,
  type LodLevel,
  type LodDecision,
  type RenderBatch,
  type EditorCommand,
  type HistoryEntry as ProfessionalHistoryEntry,
  type CommandContext,
  type MementoAdapter,
  type FloorPlanFileMetadata,
  type FloorPlanFileEnvelope,
  type FloorPlanFileEnvelopeV1,
  type FloorPlanFileEnvelopeV2,
  type PdfExportModel,
  type IndustryImportResult,
} from './professional';
